name: "deploy"
on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  docker-deploy:
    runs-on: ubuntu-latest
    env:
      BUILD_STAGE: ${{ github.event.pull_request.base.ref || github.ref_name }}
      AWS_REGION: eu-west-1
      SERVICE: syndio-docker

    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::651762338902:role/GithubActionsDeployDocker
          role-session-name: GithubActionsDeployDocker
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Docker
        run: |-
          SERVICE=${{ env.SERVICE }} BUILD_STAGE=${{ env.BUILD_STAGE }} AWS_REGION=${{ env.AWS_REGION }} bash docker-deploy.sh
